<?php

return [
    'table_name' => 'products',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `products`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `products` (
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `description` TEXT,
        `price` decimal(6,2),
        `stock` int(11),
        `color` varchar(120),
        `created_at` timestamp NOT NULL,
        `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted_at` timestamp DEFAULT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `products` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `products` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `products` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array(
            [
                'id' 			=> '1',
                'name' 			=> 'Zoete kersen',
                'description' 	=> 'Kom zoveel kersen plukken als u wil voor een vaste prijs! De kersen zijn erg zoet',
                'image' 	=> 'kersen.jpg',
                'price' 	=> '7.00',
                'stock' 	=> '50',
                'created_at' 	=> '2022-01-11 09:57:47',
                'updated_at' 	=> '2022-01-11 10:01:54',
            ],
            [
                'id' 			=> '2',
                'name' 			=> 'Sappige pruimen',
                'description' 	=> 'Met deze pruimen maak je de lekkerste taart. De ladder staat al klaar. Waar wacht u nog op?',
                'image' 	=> 'pruimen.jpg',
                'price' 	=> '4.00',
                'stock' 	=> '20',
                'created_at' 	=> '2022-01-11 09:03:51',
                'updated_at' 	=> '2022-01-11 10:05:43',
            ],
            [
                'id' 			=> '3',
                'name' 			=> 'Paprika',
                'description' 	=> 'De paprika oogst is dit jaar wat magertjes. Graag niet meer dan 2 per klant.',
                'image' 	=> 'paprika.jpg',
                'price' 	=> '2.00',
                'stock' 	=> '10',
                'created_at' 	=> '2022-01-11 09:06:06',
                'updated_at' 	=> '2022-01-11 10:07:12',
            ],
            [
                'id' 			=> '4',
                'name' 			=> 'Cherrytomaatjes',
                'description' 	=> 'Deze cherrytomaatjes mogen niet ontbreken in uw salade. Zongerijpt en biologisch.',
                'image' 	=> 'salade.jpg',
                'price' 	=> '5.00',
                'stock' 	=> '70',
                'created_at' 	=> '2022-01-11 09:07:14',
                'updated_at' 	=> '2022-01-11 10:08:09',
            ],
            [
                'id' 			=> '5',
                'name' 			=> 'Groentenpakket',
                'description' 	=> 'Speciaal voor gasten die slecht ter been zijn maken wij ook een groentenpakket.',
                'image' 	=> 'artisjok.jpg',
                'price' 	=> '8.00',
                'stock' 	=> '50',
                'created_at' 	=> '2022-01-11 09:08:14',
                'updated_at' 	=> '2022-01-11 10:09:14',
            ],
            [
                'id' 			=> '6',
                'name' 			=> 'Zure appels',
                'description' 	=> "Deze Granny's zijn lichtzuur van smaak en klaar om geplukt te worden.",
                'image' 	=> 'appels.jpg',
                'price' 	=> '10.00',
                'stock' 	=> '11',
                'created_at' 	=> '2022-01-11 09:09:17',
                'updated_at' 	=> '2022-01-11 10:10:18',
            ],
            [
                'id' 			=> '7',
                'name' 			=> 'Bloemkool',
                'description' 	=> 'De bloemkool is van oudsher een zeer geliefde groente. Het is een lichtverteerbare koolsoort en heeft een milde en toegankelijke smaak.',
                'image' 	=> 'bloemkool.jpg',
                'price' 	=> '8.00',
                'stock' 	=> '19',
                'created_at' 	=> '2022-01-24 17:37:27',
                'updated_at' 	=> '2022-01-24 18:44:16',
            ],
            [
                'id' 			=> '8',
                'name' 			=> 'Citroenen',
                'description' 	=> 'Citroenen hoeven er niet knalgeel uitzien om als rijp te kunnen doorgaan. Ze zien er alleen geel uit als ze koude nachten hebben doorgemaakt. ',
                'image' 	=> 'citroen.jpg',
                'price' 	=> '1.00',
                'stock' 	=> '89',
                'created_at' 	=> '2022-01-24 17:37:27',
                'updated_at' 	=> '2022-01-24 18:44:16',
            ],
            [
                'id' 			=> '9',
                'name' 			=> 'Rabarber',
                'description' 	=> 'Rabarber is een echte zomergroente die tot moes gemaakt wordt. ',
                'image' 	=> 'rabarber.jpg',
                'price' 	=> '9.00',
                'stock' 	=> '12',
                'created_at' 	=> '2022-01-24 17:45:22',
                'updated_at' 	=> '2022-01-24 18:58:20',
            ],
            [
                'id' 			=> '10',
                'name' 			=> 'Sla',
                'description' 	=> 'Sommige slasoorten bevatten een melkachtige vloeistof. Dit zorgt ervoor dat de sla iets bitter smaakt.',
                'image' 	=> 'sla.jpg',
                'price' 	=> '2.00',
                'stock' 	=> '22',
                'created_at' 	=> '2022-01-24 17:45:22',
                'updated_at' 	=> '2022-01-24 18:58:20',
            ],
            [
                'id' 			=> '11',
                'name' 			=> 'Tomaten',
                'description' 	=> 'Onze variatie aan tomaten is zo groot dat je elke dag van de week wel een andere kleur tomaat op tafel kan zetten!',
                'image' 	=> 'tomaat.jpg',
                'price' 	=> '1.00',
                'stock' 	=> '96',
                'created_at' 	=> '2022-01-24 17:59:03',
                'updated_at' 	=> '2022-01-24 19:06:03',
            ],
            [
                'id' 			=> '12',
                'name' 			=> 'Wortelen',
                'description' 	=> 'Laat de loof na het plukken aan de wortelen zitten voor een langere houdbaarheid.',
                'image' 	=> 'wortel.jpg',
                'price' 	=> '3.00',
                'stock' 	=> '88',
                'created_at' 	=> '2022-01-24 17:59:03',
                'updated_at' 	=> '2022-01-24 19:06:03',
            ],
        ),
    ]
];